# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCvt_HhKVs_jtw_elbe6DUh_hDGL5yew
"""


import gradio as gr
from google import genai
from google.colab import userdata

# Get API key automatically from Colab Secrets
API_KEY = userdata.get("GEMINI_API_KEY")

# Create Gemini client
client = genai.Client(api_key=API_KEY)


def generate_questions(topic, difficulty, number):

    if not topic.strip():
        return "Please enter a topic."

    prompt = f"""
You are an Interactive Question Generator.

Topic: {topic}
Difficulty: {difficulty}
Number of Questions: {number}

Generate exactly {number} questions.

Requirements:
- Number the questions clearly.
- Make them relevant to the topic.
- Match the selected difficulty.
- Do not provide answers.
- Keep them suitable for students.
"""

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    return response.text


interface = gr.Interface(
    fn=generate_questions,

    inputs=[
        gr.Textbox(
            label="Enter Topic",
            placeholder="Example: Python Programming"
        ),

        gr.Dropdown(
            choices=["Easy", "Medium", "Hard"],
            value="Medium",
            label="Difficulty Level"
        ),

        gr.Number(
            value=5,
            precision=0,
            label="Number of Questions"
        )
    ],

    outputs=gr.Textbox(
        label="Generated Questions",
        lines=12
    ),

    title="Interactive Question Generator",

    description="Enter a topic, select difficulty and number of questions."
)

interface.launch(share=True)
